@startuml
title System Landscape for Big Bank plc

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Enterprise_Boundary(enterprise, "Big Bank plc") {
  Person(CustomerServiceStaff, "Customer Service Staff", "Customer service staff within the bank.", $tags="Element+Person+Bank Staff")
  Person(BackOfficeStaff, "Back Office Staff", "Administration and support staff within the bank.", $tags="Element+Person+Bank Staff")
  System(MainframeBankingSystem, "Mainframe Banking System", "Stores all of the core banking information about customers, accounts, transactions, etc.", $tags="Element+Software System+Existing System")
  System(EmailSystem, "E-mail System", "The internal Microsoft Exchange e-mail system.", $tags="Element+Software System+Existing System")
  System(ATM, "ATM", "Allows customers to withdraw cash.", $tags="Element+Software System+Existing System")
  System(InternetBankingSystem, "Internet Banking System", "Allows customers to view information about their bank accounts, and make payments.", $tags="Element+Software System")
}

Person_Ext(PersonalBankingCustomer, "Personal Banking Customer", "A customer of the bank, with personal bank accounts.", $tags="Element+Person+Customer")

Rel_D(PersonalBankingCustomer, InternetBankingSystem, "Views account balances, and makes payments using", $tags="Relationship")
Rel_D(InternetBankingSystem, MainframeBankingSystem, "Gets account information from, and makes payments using", $tags="Relationship")
Rel_D(InternetBankingSystem, EmailSystem, "Sends e-mail using", $tags="Relationship")
Rel_D(EmailSystem, PersonalBankingCustomer, "Sends e-mails to", $tags="Relationship")
Rel_D(PersonalBankingCustomer, CustomerServiceStaff, "Asks questions to", "Telephone", $tags="Relationship")
Rel_D(CustomerServiceStaff, MainframeBankingSystem, "Uses", $tags="Relationship")
Rel_D(PersonalBankingCustomer, ATM, "Withdraws cash using", $tags="Relationship")
Rel_D(ATM, MainframeBankingSystem, "Uses", $tags="Relationship")
Rel_D(BackOfficeStaff, MainframeBankingSystem, "Uses", $tags="Relationship")

SHOW_LEGEND()
@enduml