@startuml
set separator none
title Internet Banking System - System Context

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>

Enterprise_Boundary(enterprise, "Big Bank plc") {
  System(MainframeBankingSystem, "Mainframe Banking System", $descr="Stores all of the core banking information about customers, accounts, transactions, etc.", $tags="", $link="")
  System(EmailSystem, "E-mail System", $descr="The internal Microsoft Exchange e-mail system.", $tags="", $link="")
  WithoutPropertyHeader()
  AddProperty("Development Team","Dev/Internet Services")
  AddProperty("Owner","Customer Services")
  AddProperty("Url","https://en.wikipedia.org/wiki/Online_banking")
  System(InternetBankingSystem, "Internet Banking System", $descr="Allows customers to view information about their bank accounts, and make payments.", $tags="", $link="")
}

Person_Ext(PersonalBankingCustomer, "Personal Banking Customer", $descr="A customer of the bank, with personal bank accounts.", $tags="", $link="")

Rel_D(PersonalBankingCustomer, InternetBankingSystem, "Views account balances, and makes payments using", $techn="", $tags="", $link="")
Rel_D(InternetBankingSystem, MainframeBankingSystem, "Gets account information from, and makes payments using", $techn="", $tags="", $link="")
Rel_D(InternetBankingSystem, EmailSystem, "Sends e-mail using", $techn="", $tags="", $link="")
Rel_D(EmailSystem, PersonalBankingCustomer, "Sends e-mails to", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml